= Neuer Release vom ZUGFeRD Validation Serive
Vadim Bauer
2014-08-01
:jbake-type: post
:jbake-status: published
:jbake-tags: Release	
:idprefix:
:linkattrs:
:1: <<Errors in the ZUGFeRD Specification Part 1, Errata 1>>
:2: <<Errors in the ZUGFeRD Specification Part 2, 2>>


Nach längerer Zeit gibt es wieder ein Update für den ZUGFeRD Validation Service: 
Nachdem es keinen ZUGFeRD Validation Service mit Konik 0.5.0 gab, soll Konik 0.6.0 der erste Release 
sein, welcher ZUGFeRD 1.0 unterstützt. 

Die aktuelle Konik Version ist zwar noch nicht ganz reif, 
gibt aber bereits einen Vorgeschmack auf das zu erwartende Ergebnis.
 
== Neuerungen

Wie ich schon in {1} und {2} geschrieben habe, ist die Validierung der Rechnung gegen das XSD 
ziemlich sinnlos und kann auch teilweise falsch sein. 
Deshalb wurden zwei weitere Arten von Validierungen hinzugefügt: Roundtrip Vergleich und Bean Validation. 

Roundtrip Vergleich:: 
	Hierbei wird das XML in das Konik Model und dann wieder zurück ins XML transformiert. 
	Danach werden die beiden XML Dateien miteinander verglichen und der Vergleich wird dargestellt. +
	Mit diesem Verfahren lässt sich erkennen, ob:	 
	- beim Einlesen Elemente weggelassen wurden, weil diese nicht spezifiziert oder im Model nicht vorgesehen sind,
	- Werte korrekt vorliegen und formatiert sind,
	- die Reihenfolge der Elemente korrekt ist.
Bean Validation::
	Konik verwendet nun Bean Validation, auch bekannt als JSR-303 bzw. JSR-349. 
	Damit lässt sich schon beim Erzeugen der Rechnung einfach feststellen, ob diese 
	konform mit der Spezifikation ist.   

== Fazit
Der akuelle Snapshot gibt einen guten Vorgeschmack auf die finale Version 0.6.0. 
Es wird daher empfohlen, Rechnungen noch einmal zu validieren. +
Noch hat die aktuelle Version einige offene Punkte: +
So ist die Entwicklung der Bean Validierung noch nicht ganz abgeschlossen. Ausserdem 
gibt es noch einige wenige Elemente, die im Rechnungsmodel noch nicht existieren.
 

