= Konik upcoming release preview
Vadim Bauer
2014-05-23
:jbake-type: post
:jbake-status: published
:jbake-tags: Release,Features
:idprefix:
:linkattrs:

== Next Konik release 0.3.0

I am currently working on the next Konik release, which will have many changes regarding the Konik model.

One big change is going to be the switch from the free text UNECE codes to Enumerations. This shift has its pros and cons.

Pros::
	- A document generated by Konik is semantically correct. +
	  You have a higher chance that another party can process your document not only read it.
	- The user can choose form code values instead of looking them up in the UNECE Database.
	
Cons::
	- You need to update to the newest Konik library every time new codes are added be UNECE.
	- If another party provides a semantically incorrect document Konik will no be able to read it.
	- The Konik user need to map internal system codes to Konik/UNECE Codes.
		
Another change will be a much simpler data model. The hierarchy of the model will become lower and thus easier to understand and work with.




