= Happy Birthday Konik 🎁
Vadim Bauer
2017-12-18
:jbake-type: post
:jbake-status: published
:jbake-tags: Update
:idprefix:
:linkattrs:
:1: https://www.heise.de/meldung/Release-Kandidat-fuer-elektronisches-Rechnungsformat-1884011.html

Vor vier Jahren ging die Konik Webseite online. Einige Wochen darauf, am 17. Januar folgte der erste öffentliche Sourcecode.
Die ersten Codezeilen für Konik wurden hingegen bereits im August 2013 geschrieben.
Auslöser hierzu war zum einen die Heise Newsmeldung: {1}[Release-Kandidat für elektronisches Rechnungsformat].
Zum anderen meine Erinnerung als ich 1998 mit der Selbständigkeit angefangen habe.


Damals bin ich das erste Mal mit einem ERP-System in Berührung gekommen und habe selbst begonnen eines zu verwenden.
Auf einmal waren Auftragswesen und Buchhaltung viel einfacher!
Damit konnte sogar jemand wie ich, der keine Ausbildung oder Erfahrung darin hatte, mein Unternehmen organisieren.
Ich habe mich damals schon darüber gewundert, dass man die Belege zwar einfach über E-Mail austauschen konnte,
aber die Verarbeitung immer noch mühselig war und das ERP in der Hinsicht keine Hilfe leistete. Das Prinzip ist
immer das Gleiche: Auf der einen Seite tippt jemand die Daten in sein ERP-System ein und erzeugt die Rechnung - und auf
der anderen Seite muss der Empfänger im Grunde genau das Gleiche abtippen, nur dieses Mal in sein ERP-System.
Die einzige Schnittstelle ist der Mensch.
Ich dachte, dass sich diese doppelte Arbeit doch reduzieren lassen muss! Ganz naiv habe ich nach Lösungen gesucht
und mit Firmen im Bereich EDI (Electronic Data Interchange) gesprochen. Diejenigen, die sich die Mühe machten
mir überhaupt zu antworten erklärten mir, dass die Idee nicht nur verrückt, sondern sehr kompliziert sei.
Deshalb hab ich mich irgendwann damit abgefunden.


Heute können dank der Konik Bibliothek über 120.000 Unternehmen und Behörden in Deutschland, Österreich
und der Schweiz ZUGFeRD konforme Rechnungen verarbeiten. Diese Zahl berechnet sich anhand ERP Softwarehersteller,
von denen wir wissen dass sie die Konik Bibliothek einsetzen und die Anzahl Softwareinstallationen und Nutzer dieser ERPs.

== Statistiken
In den letzten elf Monaten wurde die Konik Bibliothek 5’345 mal von 942 verschiedenen IP Adressen heruntergeladen.

== Wie geht es weiter in 2018?
Aktuell arbeiten wir an Konik 2.0, welche EN 16931, ZUGFeRD 2.0 und XRechnung konforme Rechnungen erzeugen wird.
Die kommede Version sollte aller voraussicht nach anfang des Jahres 2018 herauskommen.
Zusätzlich kommt Konik 2.0 mit einigen interessante Funktionen daher, welche die Integration in bestehende Systeme noch einfacher machen soll.





