= Unterschiede zwischen ZUGFeRD 1.0 und ZUGFeRD 2.0
Vadim Bauer
2019-03-15
:jbake-type: post
:jbake-status: draft
:jbake-tags: ZUGFeRD 2.0
:idprefix:
:linkattrs:

Unterschiede zwischen ZUGFeRD 1.0 und ZUGFeRD 2.0

Folgende Änderungen sind in der ZUGFeRD 2.0-Spezifikation im Hinblick auf die Version 1.0 zu beachten:

== Design-Prinzipien der EN 16931-1
- Bis zum Profil EN 16931 (COMFORT) gelten die Design-Prinzipien der Norm, dass sich
eine Rechnung immer nur auf genau eine Bestellung und genau eine Lieferung beziehen darf. Dies führt ggf. zu einem Änderungsbedarf in den Rechnungsstellungs- prozessen beim Sender und zu geänderten Verarbeitungsprozessen beim Empfänger.
- Für Sammelrechnungen (z.B. mehrere Bestellbezüge, mehrere Lieferorte etc.) muss das Profil EXTENDED genutzt werden.
- Anders als in ZUGFeRD 1.0 schreibt die EN 16931-1 – und somit auch ZUGFeRD 2.0 – den Nettopreis als verbindliche Preisinformation vor. Der Nettopreis des Artikels in diesem Zusammenhang ist der Preis eines Artikels ohne Umsatzsteuer nach Abzug des Nachlasses auf den Artikelpreis. Der Nettobetrag der Rechnungsposition ist der „Netto“-Betrag d. h. ohne die Umsatzsteuer, aber einschließlich aller für die Positionsebene geltenden Zu- und Abschläge sowie sonstiger anfallender Steuern. Der Grundbetrag für die prozentuale Berechnung von Zu- und Abschlägen auf Ebene der Rechnungsposition wird absolut angegeben. Die EN 16931-1 macht keine Vorgaben, wie dieser Grundbetrag berechnet werden soll.

== Abweichungen in den Profilen
- Da das COMFORT-Profil von ZUGFERD 1.0 nicht „compliant“ ist zum Datenmodell der
EN 16931-1, mussten bestimmte Elemente ergänzt oder auch weggelassen werden
(siehe Anlage).
- Änderungen im Profil EN 16931 (COMFORT) von ZUGFeRD 2.0 wirken sich auf das
Profil EXTENDED aus, da dieses eine „conformant“ Erweiterung der EN 16931-1 darstellt. Insbesondere müssen Pflichtangaben des Profils EN 16931 (COMFORT) ebenfalls Pflichtangaben im Profil EXTENDED sein.
- Die beiden ZUGFeRD 2.0-Profile BASIC WL und MINIMUM wurden aus Factur-X übernommen. In Deutschland stellen diese ausschließlich Buchungshilfen dar, d.h. es darf nur der Dokumententyp „751“ genutzt werden. In Frankreich können für die Profile BASIC WL und MINIMUM alle für die Rechnung vorgesehenen Dokumenten- typen genutzt werden, da in Frankreich nicht zwingend alle Rechnungsdaten der Bild- Repräsentanz auch in der Daten-Repräsentanz (XML-Instanz) enthalten sein müssen.
- In der EN 16931-1 werden alle Beträge in der Rechnungswährung angegeben. Diese wird auf Dokumentenebene festgelegt. Einzige Ausnahme ist der Gesamtbetrag der Umsatzsteuer, die zusätzlich auch in einer zweiten Währung, die für die Buchhaltung maßgeblich ist, angegeben werden kann. Dieses Prinzip wurde auch für das EXTENDED Profil übernommen.
- Analog zur EN 16931-1 können Rechnungsperioden von ZUGFeRD 2.0 nur noch auf Positionsebene angegeben werden, nicht mehr auf Dokumentenebene. Dies gilt auch für das EXTENDED Profil.
- Bei den Zahlungsinstrumenten wird die deutsche Bankleitzahl nicht mehr unterstützt. Nationale Kontonummern und nationale Bankleitzahlen werden analog zur
EN 16931-1 nur noch für Überweisungen unterstützt.
 0319  2019 Arbeitsgemeinschaft für Wirtschaft und Verwaltung e.V. Seite 31 von 35
ZUGFeRD 2.0 Spezifikation
 - Die EN 16931-1 unterstützt nur Nachlass auf den Bruttopreis des Artikels. Im EXTENDED Profil wird zusätzlich ein Zuschlag auf den Bruttopreis des Artikels unterstützt. Deshalb muss im EXTENDED Profil bei der Nutzung dieses Informations- elementes der „Charge Indicator“ genutzt werden, um anzugeben, ob es sich um einen Zu- oder Abschlag handelt. Der „Charge Indicator“ kann bis zum Profil
EN 16931 (COMFORT) optional genutzt werden, aber dann immer nur mit dem Wert „false“ für einen Abschlag (Nachlass).

== Geschäftsregeln
- Die Geschäftsregeln sind in der Norm EN 16931-1 formalisiert und werden in der
Beschreibung des Technischen Anhangs bei den betroffenen Business Terms explizit
angegeben. In ZUGFeRD 1.0 wurden diese Regeln im Basisdokument beschrieben.
- Geschäftsregeln, die die verschiedenen Steuerkategoriecodes betreffen, müssen der
EN 16931-1 direkt entnommen werden.
- Für das Profil EXTENDED wurden keine gesonderten Geschäftsregeln definiert (weder
in ZUGFeRD 1.0 noch in ZUGFeRD 2.0).
- Zur Prüfung dieser Regeln werden für ZUGFeRD 2.0 Schematron-Dateien veröffent-
licht.

== Kalkulationsmethode
- Die Kalkulationsmethoden sind in den Geschäftsregeln hinterlegt.
- Kalkulationsbeispiele können der Norm EN 16931-1 direkt entnommen werden und
wurden nicht in den Fließtext der ZUGFeRD 2.0 Spezifikation übernommen.

== Zulässige Steuerarten
- In ZUGFeRD 2.0 wird bis zum Profil EN 16931 (COMFORT) nur die Steuerart
„Umsatzsteuer“ mit dem Code „VAT“ unterstützt.
- Sollen andere Steuerarten angegeben wie beispielsweise eine Versicherungssteuer
oder eine Mineralölsteuer werden, muss das EXTENDED Profil genutzt werden. Der Code für die Steuerart muss dann der Codeliste UNTDID 5153 entnommen werden.

== Andere Tags im Syntaxmapping
- Aufgrund von Entscheidungen bei UN/CEFACT zur Vereinfachung der „Name and
Design Rules“ weisen die aus dem Supply Chain Reference Data Model (einer
Untermenge der Core Component Library) abgeleiteten Tags Unterschiede auf.
- Das ZUGFeRD 2.0 -Schema hat daher eine neue Struktur nach dem CII 16B Schema
und dadurch beispielsweise auch ein neues Root-Element, `CrossIndustryInvoice`.

== Codelisten
- Die unterstützten Codes werden nicht mehr in einem gesonderten Dokument
beschrieben, sondern sind den Datentypen im technischen Anhang zugeordnet.
- Codelisten, die von ZUGFeRD 2.0 vollständig unterstützt werden, werden nur
referenziert.
- Bei Datentypen, die nur eine Auswahl von Codes unterstützen, wird die abschlie-
ßende Liste der unterstützten Codes im technischen Anhang bei den jeweiligen
Business Terms angegeben.
- Die Codelisten werden zusammen mit dem Schema im Genericode-Format
veröffentlicht.
 0319  2019 Arbeitsgemeinschaft für Wirtschaft und Verwaltung e.V. Seite 32 von 35
- Die Codeliste für die Steuerart, die bis zum Profil EN 16931 (COMFORT) nur den fixen Wert „VAT“ haben kann, wurde im EXTENDED Profil auf die gesamte Codeliste UNTDID 5153 erweitert.

== Einbettung in PDF/A-3
- Der Name der eingebetteten Datei lautet weiterhin zugferd-invoice.xml.
- Das Metadatenschema ZUGFeRD PDFA Extension Schema hat sich geändert, hier ist
die ZUGFeRD-Version 2p0 angegeben.
- Rechnungsbegründende Unterlagen, die in das PDF eingebettet werden, werden aus
der XML-Datei über einen relativen Pfad referenziert.