= Impressum
Vadim Bauer
2014-5-25
:jbake-type: page
:jbake-status: published
:idprefix:
:meta_keywords: Konik Legal Notice
:meta_description:  Information disclosure about the publisher.
:meta_robots: noindex, nofollow

== Contact

Bauer Engineering+
Kleindorf 18 +
CH-8702 Zollikon +
 
== Disclaimer

The author reserves the right not to be responsible for the correctness, accuracy, timeliness, reliability or completeness 
of the information. Liability claims against the author due to material or immaterial nature, are arising from access to, 
use or non-use of the information published through misuse of the connection or technical faults will be excluded. 
All offers are non-binding. The author reserves itself it expressly to change parts of the pages or the entire offer 
without separate announcement to supplement to delete or the publication temporarily or permanently.

== Liability for links

References and links to third party websites are not our responsibility. 
Access to and use of such websites is entirely at the user’s own risk.


== Copyright

The copyright and any other rights relating to texts, illustrations, photos or any other files on the site belong exclusively 
Vadim Bauer or the mentioned owners. For Any reproduction requires the written permission of the copyright holder must be 
obtained in advance.


== Privacy Policy
Based on Article 13 of the Swiss Federal Constitution and the data protection regulations of the Federation 
(Data Protection Act, DSG) everyone has the right to privacy and to protection against misuse of their personal data. 

I comply with these provisions. Personal data will be kept strictly confidential and not sold to third parties nor disclosed.

== Privacy Statement for the Use of Google Analytics

This website uses Google Analytics, a web analysis service provided by Google Inc. (“Google”). 
Google Analytics makes use of so-called “cookies” or text files, which are stored on your computer and enable user 
interaction with website content to be measured and analysed. Information generated by the cookie about your interaction 
with this website is usually transferred to and stored on a Google server located in the US.

If IP anonymisation is activated on this website, Google will abbreviate your IP address in advance within member states 
of the European Union or other contracting parties to the Agreement of the European Economic Area. The complete IP address 
is only transferred to a Google server in the US and abbreviated there in exceptional cases. On behalf of the operator of 
this website, Google will use this information to measure your interaction with the website, compile reports about website 
activities for their operators and provide other services related to the use of the website and of the Internet. 
The IP address conveyed by your browser within the context of Google Analytics will not be linked to any other Google data.

You can choose to prevent cookies from being saved on your computer by making the appropriate settings in your browser 
software; however we would like to point out that this might prevent you from using all of the functions of this website. 
You can also prevent the data generated by the cookie about your interaction with the website (incl. your IP address) 
from being conveyed to Google and being processed by Google by downloading and installing a browser plug-in.