= ZUGFeRD
Vadim Bauer
2014-5-25
:jbake-type: page
:jbake-status: published
:meta_keywords: Definition ZUGFeRD, Was ist ZUGFeRD, ZUGFeRD Verfahren
:meta_description: Das Ziel, Definition, Entstehung und Konzept hinter ZUGFeRD



ZUGFeRD (Zentraler User Guide Forum elektronische Rechnung Deutschland) ist eine technische Spezifikation für das gleichnamige Format zum Austausch elektronischer Rechnungen. Das Format wurde vom FeRD in Zusammenarbeit mit Verbänden, Ministerien und Unternehmen entwickelt. Am 25 Juni 2014 wurde die Version 1.0 der Spezifikation veröffentlicht.

Das ZUGFeRD-Format wird nach Maßgabe des FeRD sowohl Unternehmen als auch der öffentlichen Verwaltung frei zugänglich gemacht und zu fairen, sachgerechten und nicht diskriminierenden Bedingungen angeboten.

== Ziel
ZUGFeRD konforme Rechnungen sollen zwischen Unternehmen sowie zwischen Unternehmen und der öffentlichen Verwaltung schnell, komfortabel und auf elektronischem Wege einfach ausgetauscht werden. Die Zielgruppe von ZUGFeRD sind, neben großen und mittleren Unternehmen sowie der öffentlichen Verwaltung, insbesondere auch kleine oder kleinste Unternehmen, die eine geringe Anzahl an Rechnungen stellen; respektive sogar mit Partnern zu tun haben, mit denen kein regelmäßiger Geschäftskontakt besteht.

Dabei wird erwartet, dass durch das neue ZUGFeRD-Format nicht nur die Kosten der Rechnungsstellung, aufgrund des Wegfalls von Material und Portokosten sowie einer automatischen Verarbeitung, stark reduziert bzw. komplett eliminiert werden, sondern auch das Rechnungswesen in Zukunft durch optimierte Prozesse wesentlich effizienter wird.


== Entstehung
Das Forum elektronische Rechnung Deutschland wurde unter dem Dach der Arbeitsgemeinschaft für wirtschaftliche Verwaltung e.V. gegründet. Diese wiederum wird vom Bundesministerium für Wirtschaft und Energie (BMWi) auf Beschluss des Deutschen Bundestages gefördert.
In der gegenwärtigen Form dient das FeRD als nationale Plattform von Verbänden, Ministerien und Unternehmen zur Förderung der elektronischen Rechnung in Deutschland.


== Voraussetzungen für ZUGFeRD
Die Entstehung von  ZUGFeRD wurde durch das Steuervereinfachungsgesetz 2011 begünstigt. Darin wurde die elektronischen Rechnung der klassische Papierrechnungen gleichgestellt. Zuvor musste der Empfänger die Echtheit und Unversehrtheit des Dokuments gegenüber dem Finanzamt durch Nachweis eines qualifizierten digitalen Zertifikates belegen können.
Als Alternative zur qualifizierten Signatur sind nun sogenannte „innerbetriebliche Kontrollverfahren“, die einen „verlässlichen Prüfpfad“ zwischen der Rechnung und der Lieferung gewährleisten, zulässig. Hinter dieser Definition verbirgt sich im Grunde eine klassische Rechnungseingangsprüfung, die in jedem Unternehmen ohnehin praktiziert werden muss.


== ZUGFeRD Konzept
Eine ZUGFeRD-Rechnung besteht im Wesentlichen aus zwei Teilen: Zum einen aus einer visuellen Darstellung der Rechnung für den Kunden, die in Form von PDF/a-3 erfolgt; zum Anderen aus maschinenlesbaren strukturierten Daten, die im XML-Format  dem PDF/A-3 als Anhang beigefügt werden.. Somit dient das PDF als Container sowohl für die visuelle Darstellung als auch für die strukturieren Daten im XML-Format.


== Vorteile und Abgrenzung zu bestehenden Verfahren 
Im Gegensatz zu anderen Verfahren wie EDIFACT stellt die ZUGFeRD-Spezifikation an die  Rechnungsübertragung keinerlei Anforderungen. Die ZUGFeRD-Rechnungen können so ausgetauscht werden wie es für die beiden Vertragspartner am sinnvollsten ist.  
Anders als bei EDI-Verfahren, muss bei ZUGFeRD im Vorfeld des Rechnungsaustauschs keinerlei Vereinbarung zwischn den beiden Parteien getroffen werden. Aufgrund der Änderungen im Steuervereinfachungsgesetz 2011 darf ein Rechnungssender bis auf Wiederruf elektronische Rechnungen versenden.

