:icons: font
:lnk_minimalInvoiceWeb: https://github.com/konik-io/konik/blob/konik-{konik-latest-release}/src/test/java/io/konik/examples/MinimalInvoice.java#L72
:lnk_minimal_latest: https://raw.githubusercontent.com/konik-io/konik/konik-{konik-latest-release}/src/test/java/io/konik/examples/MinimalInvoice.java

== Quick Start


The example code from {lnk_minimalInvoiceWeb}[+MinimalInvoice.java+] represents a valid basic invoice and the steps on how to convert and attach an invoice to a PDF. 

Let us step through the code and take a look at the interesting parts.

=== Creating the invoice model
[source,java,indent=-3]
----
include::{lnk_minimal_latest}[lines=72..111]
----
<1> A new invoice instance is created with one of the three allowed profiles. BASIC, COMPFORT or EXTENDED
<2> The implementation of the model as a fluent interface makes the creation of the invoice self-explanatory.

=== Transforming invoice model to XML

[source,java,indent=-3]
----
include::{lnk_minimal_latest}[lines=114..118]
----
<1> The +InvoiceTransformer+ is responsible for transforming XML to Model and vice versa.   
<2> Transform from invoice to an +OutputStream+.
 
=== Attaching invoice model to PDF
This alternative step performs a model conversation. So you don't have to do it yourself.

[source,java,indent=-3]
----
   public void creatInvoiceAndAttachToPDF() throws IOException {
      Invoice invoice = createMinimalInvoiceModel();
      PdfHandler handler = new PdfHandler();    // <1>
      InputStream inputPdf = getClass().getResourceAsStream("/acme_invoice-42.pdf");
      OutputStream resultingPdf = new FileOutputStream("target/acme_invoice-42_ZUGFeRD.pdf");
      handler.appendInvoice(invoice, inputPdf, resultingPdf);     // <2>
   }
----
<1> Create a new +PdfHandler+ or reuse existing.  
<2> Append Invoice to existing PDF defined in +inputPdf+ the result will be written to +resultingPdf+.
 
 
 