:icons: font

== Konik Configuration

Konik is delivered with a sensible default configuration out of the box.
In most cases you should not need to change the default settings. 

List of default Konik configuration options.

[source,bash]
----
#default
io.konik.stripTrailingZeros=true
io.konik.jaxb.adapter.TwoDigitRoundingAdapter.scale=2
io.konik.jaxb.adapter.TwoDigitRoundingAdapter.roundingMode=HALF_UP
io.konik.jaxb.adapter.FourDigitRoundingAdapter.scale=4
io.konik.jaxb.adapter.FourDigitRoundingAdapter.roundingMode=HALF_UP
io.konik.jaxb.adapter.MeasureRoundingAdapter.scale=2
io.konik.jaxb.adapter.MeasureRoundingAdapter.roundingMode=HALF_UP
io.konik.jaxb.adapter.QuantityRoundingAdapter.scale=4
io.konik.jaxb.adapter.QuantityRoundingAdapter.roundingMode=HALF_UP
----

There are two possible ways how Konik can be configured.

=== Property file 
If a property file with the name +io.konik.configuration.properties+ exists in the root of the classpath it will be loaded when accessing the configuration.
When using maven `io.konik.configuration.properties` should be placed in `src/main/resources`.

=== System property
In addition system properties can be also used to change the Konik configuration.
Setting System Properties is either done with `-D` command line argument on application start or with 
`System.setProperty("io.konik.key","value");` within the application. 
When using the later method make sure that the property needed are set before Konik Configuration is loaded. 
[[admonition]]
[role="alert alert-info"]
+++<i class="fa fa-info-circle fa-3x col-lg-1"></i>+++
System Properties override file properties. 
This is can be useful in cases where you define a default configuration in the property file but want to have different configuration in a particular application instance.




