= Looking back on the GS1 electronic invoice practice day
Vadim Bauer
2014-06-014
:jbake-type: post
:jbake-status: published
:jbake-tags: Conference	
:idprefix:
:linkattrs:
:1: http://www.gs1-germany.de/no_cache/gs1-academy/veranstaltungen/detail/seminar/GS1-Praxistag-Elektr-1658/seminar-termin/2014-06-12_GS1-Germany-Knowledg_ID_1924/


This week I participated with Konik at the {1}[GS1 electronic invoice practice day]. When looking back on the event which
was full of talks related to electronic invoicing where many had an emphasis on ZUGFeRD. The only two presented business
cases didn’t include ZUGFeRD. During the break I didn’t had time to ask the two speakers if they had any plans to 
integrate ZUGFeRD into their electronic invoice process. I plan to catch up with them via E-mail and post results of 
the conversation.

What pleasantly surprised me was the large number of visitors. Going through the participation list of around 90 
participants I can recognize more than half of the participants were end users mainly interested in ZUGFeRD. 
From the IT side, some companies were already working or investigating with ZUGFeRD for their projects.

The atmosphere was mainly dominated by waiting for the first release with the hope of a general ZUGFeRD success before 
everyone wants to ramp up the projects. Interesting was also the fact that I didn’t see many ERP companies, 
but mostly backup and CMS vendors. Participants sometimes criticized the lack of PR for ZUGFeRD and especially the 
spread among tax consultants.

=== Conclusion
Everyone is waiting for a ZUGFeRD success to minimize risk, while everyone hopes for success because the demand is high. 
I personally think that with the Konik library the investment costs can be kept on a low level which also means 
that it is a low risk and effort to implement ZUGFeRD compliant invoicing for vendors and end users.

